name: Secret Test

on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Show secrets
        run: |
          echo "Username: ${{ secrets.FTP_USERNAME }}"
          echo "Password: ${{ secrets.FTP_PASSWORD }}"
